front:
  build: ./node_modules/node-front-controller
  volumes:
    - "front-controller:/src/app"
  ports:
    - "80:3000"
  links:
   - api
api:
  build: ./node_modules/node-sample-redis-api
  volumes:
    - "test-app:/src/app"
  ports:
    - "3000:3000"
  links:
   - redis
redis:
    build: ./redis
    ports:
        - "6379:6379"
