front:
  build: ./node_modules/node-front-controller
  volumes:
    - "front-controller:/src/app"
  ports:
    - "80:3000"
  links:
   - mongoapi
   - redisapi
mongoapi:
  build: ./node_modules/node-sample-mongodb-api
  ports:
    - "3001:3000"
  links:
    - mongodb
mongodb:
    build: ./mongodb
    environment:
      - AUTH=no
    ports:
      - "27017:27017"
redisapi:
  build: ./node_modules/node-sample-redis-api
  volumes:
    - "test-app:/src/app"
  ports:
    - "3002:3000"
  links:
   - redis
redis:
    build: ./redis
    ports:
        - "6379:6379"
